# Environment yaml of the collatz library
name: collatz
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - pandas
  - python>=3.8.2
  - pytest
  - pytest-cov
  - pylint
  - networkx
  - pydot
  - jupyter
  - scikit-learn
  - pydotplus