# YAML for setting up a conda environment for
# the Collatz library
name: collatz
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - pandas
  - python>=3.8.2
  - pytest
  - pytest-cov
  - pylint
  - networkx
  - pydot
  - pydotplus
  - plotly
  - tensorflow-gpu
  - jupyter
  - jupytext
  - scikit-learn
  - sympy